2018-01-25 14:43:20,765 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2018-01-25 14:43:20,922 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2018-01-25 14:43:37,272 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2018-01-25 14:43:40,319 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2018-01-25 14:43:47,063 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2018-01-25 14:44:06,635 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: HTTPConnectionPool(host='python.jobbole.com', port=80): Read timed out.
2018-01-25 14:44:09,013 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: HTTPConnectionPool(host='python.jobbole.com', port=80): Read timed out.
2018-01-25 15:54:35,041 - /home/linhui/systemcode/spider_system/spider_system/utils/request.py - INFO - http://python.jobbole.com/87310/: HTTPConnectionPool(host='python.jobbole.com', port=80): Read timed out.
2018-01-26 14:35:23,202 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - ../_static/default.css: Invalid URL '../_static/default.css': No schema supplied. Perhaps you meant http://../_static/default.css?
2018-01-26 14:35:23,204 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - ../_static/default.css: Invalid URL '../_static/default.css': No schema supplied. Perhaps you meant http://../_static/default.css?
2018-01-26 14:35:44,943 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - ../_static/default.css: Invalid URL '../_static/default.css': No schema supplied. Perhaps you meant http://../_static/default.css?
2018-01-26 14:35:44,945 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - ../_static/default.css: Invalid URL '../_static/default.css': No schema supplied. Perhaps you meant http://../_static/default.css?
2018-01-26 14:37:12,959 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:37:12,960 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:38:22,576 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:38:22,577 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:39:35,697 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:39:35,699 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:40:40,814 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:40:40,817 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:41:45,897 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:41:45,898 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - //www.baidu.com/more/: Invalid URL '//www.baidu.com/more/': No schema supplied. Perhaps you meant http:////www.baidu.com/more/?
2018-01-26 14:56:10,762 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://www.bj.cyberpolice.cn/index.htm: HTTPConnectionPool(host='www.bj.cyberpolice.cn', port=80): Max retries exceeded with url: /index.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6a89a3b630>, 'Connection to www.bj.cyberpolice.cn timed out. (connect timeout=15)'))
2018-01-26 14:56:25,787 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://www.bj.cyberpolice.cn/index.htm: HTTPConnectionPool(host='www.bj.cyberpolice.cn', port=80): Max retries exceeded with url: /index.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6a89a481d0>, 'Connection to www.bj.cyberpolice.cn timed out. (connect timeout=15)'))
2018-01-26 14:58:31,770 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://blog.csdn.net/preyta/article/details/54288870: HTTPConnectionPool(host='blog.csdn.net', port=80): Max retries exceeded with url: /preyta/article/details/54288870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f98497e69b0>, 'Connection to blog.csdn.net timed out. (connect timeout=15)'))
2018-01-26 14:59:54,196 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://blog.csdn.net/preyta/article/details/54288870: HTTPConnectionPool(host='blog.csdn.net', port=80): Max retries exceeded with url: /preyta/article/details/54288870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f289a54d978>, 'Connection to blog.csdn.net timed out. (connect timeout=15)'))
2018-01-26 15:00:09,219 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://blog.csdn.net/preyta/article/details/54288870: HTTPConnectionPool(host='blog.csdn.net', port=80): Max retries exceeded with url: /preyta/article/details/54288870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f289a568128>, 'Connection to blog.csdn.net timed out. (connect timeout=15)'))
2018-01-26 15:00:34,302 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://blog.csdn.net/preyta/article/details/54288870: HTTPConnectionPool(host='blog.csdn.net', port=80): Max retries exceeded with url: /preyta/article/details/54288870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f05917319b0>, 'Connection to blog.csdn.net timed out. (connect timeout=15)'))
2018-01-26 15:00:49,608 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://blog.csdn.net/preyta/article/details/54288870: HTTPConnectionPool(host='blog.csdn.net', port=80): Max retries exceeded with url: /preyta/article/details/54288870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f059175b278>, 'Connection to blog.csdn.net timed out. (connect timeout=15)'))
2018-01-26 15:02:06,187 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://blog.csdn.net/preyta/article/details/54288870: HTTPConnectionPool(host='blog.csdn.net', port=80): Max retries exceeded with url: /preyta/article/details/54288870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3a753c4978>, 'Connection to blog.csdn.net timed out. (connect timeout=15)'))
2018-01-26 15:02:24,858 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3623d0320>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:02:24,861 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3623d0940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:02:33,974 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc36138a940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:02:33,976 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc36138a588>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:03:49,869 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://oss.oetiker.ch/rrdtool/: HTTPSConnectionPool(host='oss.oetiker.ch', port=443): Read timed out. (read timeout=15)
2018-01-26 15:04:06,766 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://oss.oetiker.ch/rrdtool/: HTTPSConnectionPool(host='oss.oetiker.ch', port=443): Read timed out. (read timeout=15)
2018-01-26 15:05:45,568 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://feeds.feedburner.com/sonatype: HTTPConnectionPool(host='feeds.feedburner.com', port=80): Max retries exceeded with url: /sonatype (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc361251208>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
2018-01-26 15:06:00,592 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://feeds.feedburner.com/sonatype: HTTPConnectionPool(host='feeds.feedburner.com', port=80): Max retries exceeded with url: /sonatype (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc361251be0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
2018-01-26 15:17:28,833 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ce9b23e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:17:28,836 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ce9ab5080>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:18:02,413 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a6229b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:18:02,415 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a6229240>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:18:14,286 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a51c8fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:18:14,288 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72a51ce518>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:18:57,811 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6b3de3e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-26 15:18:57,813 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://localhost:5555: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6b3d75080>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-01-31 14:49:48,902 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://news.ifeng.com/listpage/70374/1/list.shtml?_zbs_baidu_news: HTTPConnectionPool(host='news.ifeng.com', port=80): Read timed out. (read timeout=15)
2018-01-31 14:50:03,939 - /home/linhui/kumo/spiders/spider_system/utils/request.py - INFO - http://news.ifeng.com/listpage/70374/1/list.shtml?_zbs_baidu_news: HTTPConnectionPool(host='news.ifeng.com', port=80): Read timed out. (read timeout=15)
